version: '3.1'

services:

  db:
    image: mysql
    container_name: mysql-course
    command: --default-authentication-plugin=mysql_native_password
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - spring_data:/var/lib/mysql
    mem_limit: 1024m

volumes:
  spring_data: